### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by kstandage** [DBHeise/fileid#12]
Do you have any binaries you can share? Going to the link to the build server only shows binaries from the successful jobs, which are now expired.
Any chance you can add them to the Releases section?

**Comment by sergeevabc** [comment]
Err… @DBHeise, are you there? Hello?

**Comment by DBHeise** [comment]
will add auto releases from the build artifacts...eta sometime this week...

**Comment by DBHeise** [comment]
this [commit](https://github.com/DBHeise/fileid/commit/9f61b5967bb7a2f4a6cfa30effb08ae6758d1ab3) added auto bundling of built binaries to the ["latest" release](https://github.com/DBHeise/fileid/releases/tag/latest)
