### ISSUE TITLE
Add support for the most common file types

### ISSUE THREAD

**Issue by DBHeise** [DBHeise/fileid#3]
Add basic detection for the following list of common file formats
[Wikipedia](https://en.wikipedia.org/wiki/List_of_file_formats)
[FileInfo](http://fileinfo.com/filetypes/common)
[NMU](http://it.nmu.edu/docs/common-windows-file-extensions)

**Comment by Sicos1977** [comment]
See --> https://github.com/Sicos1977/MSGReader/blob/master/MsgReader/Helpers/FileTypeSelector.cs

**Comment by DBHeise** [comment]
Closing this as the focus of the project has been better defined, each file format should be a separate issue to get it to the desired coverage level (Identification, Meta1-10, Full)
